In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
pip show numpy

Name: numpy
Version: 1.18.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\pooja\anaconda3\lib\site-packages
Requires: 
Required-by: tables, statsmodels, seaborn, scipy, scikit-learn, PyWavelets, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy
Note: you may need to restart the kernel to use updated packages.


To create an array using the list, use the following syntax.

Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements.
In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be accessed by using the 0 based indexing.
Each element of the Array object contains the same size in the memory.

In [1]:
import numpy 
a = numpy.array([1, 2, 3])  
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
To create a multi-dimensional array object, use the following syntax.

In [4]:
 a = numpy.array([[1, 2, 3], [4, 5, 6]])   
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


To change the data type of the array elements, mention the name of the data type along with the collection.

In [2]:
a = numpy.array([1, 3, 5, 7], complex)  
print(a)
print(type(a))

[1.+0.j 3.+0.j 5.+0.j 7.+0.j]
<class 'numpy.ndarray'>


Finding the dimensions of the Array
The ndim function can be used to find the dimensions of the array.

In [3]:
import numpy as np  
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23], [14,15,16,17]])  
  
print(arr.ndim)  
print(arr)

2
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 23]
 [14 15 16 17]]


Finding the size of each array element
The itemsize function is used to get the size of each array item. It returns the number of bytes taken by each array element.

In [10]:
a = np.array([[1,2,3]])  
print(a.itemsize)
print("Each item contains",a.itemsize,"bytes")  

4
Each item contains 4 bytes


## Dtype- Data type of elements

Finding the data type of each array item
To check the data type of each array item, the dtype function is used.


In [7]:
a = np.array([[1,2,3]])  
print("Each item is of the type",a.dtype)           #dtype- Datatype of elements

Each item is of the type int32


Finding the shape and size of the array
To get the shape and size of the array, the size and shape function associated with the numpy array is used.

In [14]:
a = np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])  
print("Array Size:",a.size)  
print("Shape:",a.shape)  
print(a)
a=a.reshape(7,2)
print(a)

Array Size: 14
Shape: (2, 7)
[[1 2 3 4 5 6 7]
 [2 3 4 5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 2]
 [3 4]
 [5 6]
 [7 8]]


Reshaping the array objects
the numpy module provides us the way to reshape the array
by changing the number of rows and columns of the multi-dimensional array.
The reshape() function associated with the ndarray object is used to reshape the array. It accepts the two parameters indicating the row and columns of the new shape of the array.

In [13]:
a = np.array([[1,2],[3,4],[5,6]])  
print("printing the original array..")  
print(a)  
a=a.reshape(2,3)  
print("printing the reshaped array..")  
print(a)  

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


Slicing in the Array
Slicing in the NumPy array is the way to extract a range of elements from an array. 
Slicing in the array is performed in the same way as it is performed in the python list.

In [14]:
a = np.array([[1,2],[3,4],[5,6]])  
print(a[0,1])  
print(a[2,0])  

2
5


Linspace
The linspace() function returns the evenly spaced values over the given interval.
The following example returns the 10 evenly separated values over the given interval 5-15

In [22]:
a=np.linspace(5,15,10) #prints 10 values which are evenly spaced over the given interval 5-15  
print(a)  

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [ ]:
1- Define an array of 7 rows and 3 columns, any numbers
get the datatype of elements
specify the itemsize of array
slice the elements - 2nd row 2nd column elements, 3rd row 3rd column,7th row 1st column
reshape the array to 3 rows and 7 columns

2-Explore salary data
find relationship between variables
plot histogram
plot box plot